Repository csivitu/ArcadeGames, pull requests merged in 2022-10, with the labels that each got.

#56 Game Over ( SpaceInvaders - Python ) #36
  pythongames/spaceinvaders/main.py
Labels: hacktoberfestapproved

#69 Time Limit ( Snake - Python ) #39
  pythongames/snake/snake.py
Labels: hacktoberfestapproved

#61 Docs: #45 ReadMe Created For TicTacToe (JS)
  jsgames/tictactoe/README.md
Labels: hacktoberfestapproved

#64 [BUG] Shooting ( SpaceInvaders - Python ) #35
  pythongames/spaceinvaders/main.py
Labels: hacktoberfestapproved

#83 Speed Increase ( SpaceInvaders - Python ) #34
  pythongames/spaceinvaders/main.py
Labels: hacktoberfestapproved

#87 [Enhancement] Levels ( Hangman - Java ) #37
  javagames/hangmangame/Hangman.java
Labels: hacktoberfestapproved

#88 [Feat] Add Pacman #86
  pythongames/Pacman/Pacman.py
Labels: hacktoberfest-approved

#90 [Feat] : Adding timelimit for each point (snake - python) #89
  pythongames/snake/snake.py
Labels: hacktoberfest-approved

#97 feat: Added a new crappy jsgame
  jsgames/bees_game/index.html
  jsgames/bees_game/src/css/main.css
  jsgames/bees_game/src/img/gegnerfigur.png
  jsgames/bees_game/src/img/humangegner.png
  jsgames/bees_game/src/img/spielfigur.png
  jsgames/bees_game/src/img/zielbereich.png
  jsgames/bees_game/src/js/main.js
Labels: hacktoberfest-approved

#94 Feat : asteroid (init)
  .DS_Store
  .idea/ArcadeGames.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  pythongames/.DS_Store
  pythongames/Asteroids/arcade-game.png
  pythongames/Asteroids/asteroids.py
  pythongames/Asteroids/battleship.png
Labels: hacktoberfest-approved

#100 Added contributors details with profile pics.
  README.md
Labels: hacktoberfest, hacktoberfest-approved

#109 feat : Added a new game in csharp
  csharpgames/Checkers.csproj
  csharpgames/Checkers.sln
  csharpgames/Program.cs
Labels: hacktoberfest, hacktoberfest-approved

#117 feat : added a description for checkers game
  csharpgames/README.md
Labels: hacktoberfest

#116 Feat#115 Add sliding_puzzle javascript game
  jsgames/sliding_puzzle/index.html
Labels: hacktoberfest-approved

#124 added README.md for Asteroids.
  pythongames/Asteroids/README.md
Labels: hacktoberfest, hacktoberfest-approved

#125 added README.md for Blackjack.
  pythongames/blackjack/README.md
Labels: hacktoberfest, hacktoberfest-approved

#128 Bombardment (Game on Java)
  javagames/Bombardment/Bombardment.java
  javagames/Bombardment/BombardmentGame.java
Labels: hacktoberfest, hacktoberfest-approved

#130 feat : made a queen game
  pythongames/queen/.flake8
  pythongames/queen/queen.py
Labels: hacktoberfest, hacktoberfest-approved

#111 Hangman game added
  jsgames/Hangman/index.html
  jsgames/Hangman/script.js
  jsgames/Hangman/style.css
Labels: hacktoberfest, hacktoberfest-approved

#133 Feat: made a readme file
  javagames/towers/README.md
  pythongames/queen/README.md
Labels: hacktoberfest, hacktoberfest-approved

#135 feat : added a readme for bombardment
  javagames/Bombardment/README.md
Labels: hacktoberfest, hacktoberfest-approved

#136 feat : made a readme for horserace
  jsgames/horserace/README.md
Labels: hacktoberfest, hacktoberfest-approved

#138 feat : made HighIQ in java
  javagames/HighIQ/HighIQ.java
  javagames/HighIQ/HighIQGame.java
Labels: hacktoberfest, hacktoberfest-approved

#139 feat : made a readme for HighIQ
  javagames/HighIQ/README.md
Labels: hacktoberfest, hacktoberfest-approved

#137 feat: Add Pacman Javascript
  jsgames/pacman_game/app.js
  jsgames/pacman_game/index.html
  jsgames/pacman_game/style.css
Labels: hacktoberfest, hacktoberfest-approved

#140 feat: snake
  javagames/snake/snake.png
  javagames/snake/src/com/zetcode/Board.java
  javagames/snake/src/com/zetcode/Snake.java
  javagames/snake/src/resources/apple.png
  javagames/snake/src/resources/dot.png
  javagames/snake/src/resources/head.png
Labels: hacktoberfest, hacktoberfest-approved

#141 feat: hangman
  c-lang/hangman.c
  c-lang/images/screenshot.png
Labels: hacktoberfest-approved

#145 feat: added hangman in golang
  golangames/hangman.go
Labels: hacktoberfest, hacktoberfest-approved

#147 feat: added tic tac toe in clang
  c-lang/tictactoe.c
Labels: hacktoberfest, hacktoberfest-approved

#150 feat: snake game in clang
  c-lang/snakegame.c
Labels: hacktoberfest, hacktoberfest-approved

#149 feat: made a piano tiles game
  htmlgames/piano tiles/index.html
  htmlgames/piano tiles/script.js
  htmlgames/piano tiles/styles.css
Labels: hacktoberfest, hacktoberfest-approved

#151 feat: tic tac toe game
  htmlgames/tic-tac-toe/index.html
  htmlgames/tic-tac-toe/index.js
  htmlgames/tic-tac-toe/index.scss
Labels: hacktoberfest, hacktoberfest-approved

#152 feat : added cube game in python
  pythongames/cube/Cube.py
Labels: hacktoberfest, hacktoberfest-approved

#153 feat : made guess game in java
  javagames/guess/Guess.java
  javagames/guess/GuessGame.java
  javagames/guess/~
Labels: hacktoberfest, hacktoberfest-approved

#154 Cube game/readme
  pythongames/cube/README.md
Labels: hacktoberfest, hacktoberfest-approved

#157 feat : added hammurabi in python
  pythongames/Hammurabi/Hamurabi.py
Labels: hacktoberfest, hacktoberfest-approved

#158 feat : made dino game in javascript
  jsgames/chrome-dino/.editorconfig
  jsgames/chrome-dino/.gitignore
  jsgames/chrome-dino/.prettierignore
  jsgames/chrome-dino/.prettierrc.js
  jsgames/chrome-dino/.vscode/extensions.json
  jsgames/chrome-dino/.vscode/settings.json
  jsgames/chrome-dino/assets/PressStart2P-Regular.ttf
  jsgames/chrome-dino/assets/favicon.png
  jsgames/chrome-dino/assets/game-over.mp3
  jsgames/chrome-dino/assets/jump.mp3
  jsgames/chrome-dino/assets/level-up.mp3
  jsgames/chrome-dino/assets/preview.png
  jsgames/chrome-dino/assets/sprite.png
  jsgames/chrome-dino/index.html
  jsgames/chrome-dino/lib/actors/Actor.js
  jsgames/chrome-dino/lib/actors/Bird.js
  jsgames/chrome-dino/lib/actors/Cactus.js
  jsgames/chrome-dino/lib/actors/Cloud.js
  jsgames/chrome-dino/lib/actors/Dino.js
  jsgames/chrome-dino/lib/game/DinoGame.js
  jsgames/chrome-dino/lib/game/GameRunner.js
  jsgames/chrome-dino/lib/index.js
  jsgames/chrome-dino/lib/sounds.js
  jsgames/chrome-dino/lib/sprites.js
  jsgames/chrome-dino/lib/utils.js
  jsgames/chrome-dino/license
  jsgames/chrome-dino/package.json
  jsgames/chrome-dino/yarn.lock
Labels: hacktoberfest, hacktoberfest-approved

#159 Dino/readme
  jsgames/chrome-dino/README.md
  pythongames/Hammurabi/README.md
Labels: hacktoberfest, hacktoberfest-approved

#163 Add jokenpo game
  pythongames/Jokenpo/Jogadores.py
  pythongames/Jokenpo/Partida.py
  pythongames/Jokenpo/main.py
Labels: hacktoberfest, hacktoberfest-approved

#165 Create a README.md Hangman
  jsgames/Hangman/README.md
Labels: hacktoberfest, hacktoberfest-approved

#166 Create README.md tower
  pythongames/tower/README.md
Labels: hacktoberfest, hacktoberfest-approved

#168 README.md guess
  javagames/guess/README.md
Labels: hacktoberfest, hacktoberfest-approved
